user www-data;
worker_processes auto;
pid /run/nginx.pid;
error_log /var/log/nginx/error.log;

#include /etc/nginx/modules-enabled/*.conf;

events {
        worker_connections 1024;
        use epoll;
        multi_accept on;
}

http {
        ##
        # Basic Settings
        ##

        sendfile on;
        tcp_nopush on;
        tcp_nodelay on;
        keepalive_timeout 65;
        types_hash_max_size 2048;
        server_tokens off;

        # server_names_hash_bucket_size 64;
        # server_name_in_redirect off;

        include /etc/nginx/mime.types;
        default_type application/octet-stream;

        ##
        # SSL Settings
        ##

        #ssl_protocols TLSv1 TLSv1.1 TLSv1.2 TLSv1.3; # Dropping SSLv3, ref: POODLE
        #ssl_prefer_server_ciphers on;

        ##
        # Logging Settings
        ##
        log_format main '$remote_addr - $remote_user [$time_local] "$request" '
                        '$status $body_bytes_sent "$http_referer" '
                        '"$http_user_agent" "$http_x_forwarded_for"';

        access_log /var/log/nginx/access.log main;

        ##
        # Gzip Settings
        ##

        gzip on;

        gzip_vary on;
        gzip_proxied any;
        gzip_comp_level 6;
        gzip_buffers 16 8k;
        gzip_disable "msie6";
        gzip_http_version 1.1;
        gzip_types text/plain text/css application/json application/javascript text/xml application/rss+xml application/xml+rss
                   text/javascript font/truetype font/opentype application/vnd.ms-fontobject image/svg+xml;

        ##
        # Cache_path
        ##
        proxy_cache_path /var/cache/nginx
                levels=1:2
                keys_zone=static_cache:10m
                max_size=100m
                inactive=60m
                use_temp_path=off;

        ##
        # Virtual Host Configs
        ##

        map $host $project_root {
                default /home/directpi/21school/BE3_Nginx_Pro.ID_1269323-1/src/NginxPro;
        }
        
        upstream backend_primary {
                server localhost:8080 weight=2;
                server localhost:8081 weight=1;
                server localhost:8082 weight=1;
        }

        upstream backend_write {
                server localhost:8080;
        }

        include /etc/nginx/conf.d/*.conf;
}