[pytest]
testpaths = tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*
addopts = 
    -v
    --strict-markers
    --tb=short
    --html=reports/report.html
    --self-contained-html
markers =
    smoke: Smoke тесты - базовая проверка функциональности
    api: API тесты
    integration: Интеграционные тесты
    slow: Медленные тесты
    requires_auth: Тесты требующие авторизации



